### ISSUE TITLE
Bad behaviour while trying to kill the daemon with CTRL+C

### ISSUE THREAD

**Issue by 8102** [ava-project/ava-core#4]
There is a problem when I try to exit the daemon with ctrl+c I have to press it twice and then this error output : 
```
^CStopping the DaemonServer...
$> ^C^CTraceback (most recent call last):
  File "core/ava.py", line 13, in main
    inp = input("$> ")
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core/ava.py", line 24, in <module>
    main()
  File "core/ava.py", line 19, in main
    daemon.stop()
  File "/home/patoche/Rendu/EIP/ava-core/core/daemon/Daemon.py", line 98, in stop
    self._cv.acquire()
KeyboardInterrupt

```

**Comment by tmilox** [comment]
commit 69cc50e05259aba2cdec3d8cd5f92d10a51d10ef
